triggers:
- envs: []
  last_enabled_at: 2024-04-03 14:25:26.382685
  name: phase_3
  pipeline_uuid: trending_video_dbt
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-04-03 14:24:00
  status: active
  variables: {}
