version: 2

sources:
  - name: staging
    database:  "{{ env_var('GCS_PROJECT_NAME') }}"
    schema: country_data

    tables:
      - name: partitioned_JP
      - name: partitioned_IN
      - name: partitioned_US
