triggers:
- envs: []
  last_enabled_at: 2024-04-04 20:11:33.287680
  name: phase 1
  pipeline_uuid: trending_video_api_to_gcs
  schedule_interval: '@once'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-04-03 19:49:00
  status: active
  variables: {}
