triggers:
- envs: []
  last_enabled_at: 2024-03-29 18:24:08.144162
  name: phase_1
  pipeline_uuid: trending_video_api_to_gcs
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-03-29 18:23:00
  status: active
  variables: {}
