default:
  target: dev
  outputs:
    dev:
      dataset: country_data
      job_execution_timeout_seconds: 6000
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      method: service-account
      priority: batch
      threads: 4
      type: bigquery
